### ISSUE TITLE
[Feature] NoticeService make up

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_frontend#11]
## Title

- [Feature] NoticeService make up

## Description

- 공지사항 및 공지사항 코드 정리 및 Screen Flow Chart 정리

## TODO

- [x] : 공지사항 코드 정리, Binding 정리 및 주석
- [x] : 공지사항 댓글 코드 정리, Binding 정리 및 주석
- [x] : 공지사항, 공지사항 댓글 Screen Flow Chart 작성

## Watch out 

- 공지사항 서비스 외 다른 서비스의 코드 정리 및 수정

**Comment by leewoooo** [comment]
already resolved with #12
