### ISSUE TITLE
[Feature] Group Screen

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_frontend#15]
## Title

- [Feature] Group Screen

## Description

- Group에 대한 CRUD 페이지 및 Server API 연결하기

## TODO

- [ ] : Generic Stock 만들기
- [ ] : Group List를 볼 수 있는 Screen & Group Detail Screen 퍼블리싱 하기
- [ ] : Group에 대한 CRUD  Screen 퍼블리싱 진행하기 -> FE에서 권한 Check 하기

## Watch out 

- Group 외 다른 작업
