### ISSUE TITLE
[Feature] Splash, Login

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_frontend#16]
## Title

- [Feature] Splash, Login

## Description

- BackEnd 로직 변경으로 인한 Splash 스크린 및 인증 처리 변경

## TODO

- [ ] : 화면 Flow chart 작성하기
- [ ] : Splash Screen 주석 작성
- [ ] : Login Screen 주석 작성 및 GetX Pattern 적용
- [ ] : Auth Client (with DIO) 구현

## Watch out 

- Flow chart는 Splash & Login 까지만 작성할 것
